name: CI

on:
  push:
    branches:
      - feature/versioning

jobs:
  details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
          versionSpec: '6.3.x'

      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.2.1

      - name: Interact with version
        run: |
          echo "${{ steps.version_step.outputs.MajorMinorPatch }}"
